name: First Workflow

on:
  - push

jobs: 
  first_job: 
    name: My updated job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Updated Welcome Message
        run: echo "Welcome to the CICD world with Github actions"

      - name: List all Files including hidden
        run: ls -a

      - name: Display current working directory
        run: pwd